language: ruby

rvm:
  - 2.2.9
  - 2.3.7
  - 2.4.4
  - 2.5.1

gemfile:
  - Gemfile
  - Gemfile.rails50
  - Gemfile.rails51

notifications:
  email:
    recipients:
      - api-versions@erich.erichmenge.com
      - me@davidcel.is
